### ISSUE TITLE
Tagline header

### ISSUE THREAD

**Issue by alessandro1997** [alessandro1997/the-codeless-code#262]
This one's for @QilessQi.

I noticed case 184 has a "Tagline" header ("In which we get the big picture"). How should I handle it in the translation?

**Comment by QilessQi** [comment]
Completely optional.  :-)  I realized that when I was announcing the cases
(on Facebook or Twitter), I was habitually adding a tagline.  I've decided
to capture this in the document itself so it doesn't get lost.  Right now
the website doesn't display it, but in theory it might in the future.  I
could also opt to only display it if a version in the target language
exists, so translators need not worry about it.

Regards,

Qi

**Comment by alessandro1997** [comment]
Thanks for the explanation!
