### ISSUE TITLE
April's monks!

### ISSUE THREAD

**Issue by abelards** [alessandro1997/the-codeless-code#284]
I would like to report three plagiarisms:
- first, Randall Munroe is jealous and stealing all content to make XKCD about coding monks!
   (see any one case but 185, e.g. http://thecodelesscode.com/case/100 )
- then, @QilessQi is writing about social media (and will be encouraged to share his statistics
   with some monks in dire need of social interaction http://thecodelesscode.com/case/147 )
- Sylvain Abélard is jealous and writing fanfics (nothing erotic... yet?)
   (see http://maitre-du-monde.fr/cases/mine.html )

**Comment by QilessQi** [comment]
I look forward to reading your fanfic tonight.  As for the other stuff, I
just had one reader email me to express concern about the new site design,
and begging me to tell him that it was just an April Fool's joke.  :-)

Many regards,

Qi
