### ISSUE TITLE
'About' page not working

### ISSUE THREAD

**Issue by alessandro1997** [alessandro1997/the-codeless-code#291]
Hey @QilessQi,

the 'About' page seems to return an error.

May I also suggest hiding errors in production and logging them instead? :)

**Comment by QilessQi** [comment]
Thanks for the heads-up.  :-)    Yes, the production box run by my host
does not *quite *match my development box at home, and things that work at
home occasionally break upon deployment.  Clearly I'll have to make some
more changes.

Regards,

Qi
