### ISSUE TITLE
Translating the talks?

### ISSUE THREAD

**Issue by krzysztof-sikorski** [alessandro1997/the-codeless-code#294]
@QilessQi Do you plan to open the transcript of your ["Hacking the Mind"](http://thecodelesscode.com/talks/hacking-the-mind) talk to translations?

**Comment by QilessQi** [comment]
Absolutely!   Right now it's in HTML/PHP, which is bad for long-term
maintenance.  Let me convert it to a Wiki-like syntax, like the cases
themselves, where each slide is a section of the larger document -- that
way it can be converted to any of a number of viewable formats.

Many regards,

Qi
