### ISSUE TITLE
Case 218 - Yes, I'm tempted

### ISSUE THREAD

**Issue by galcalde** [alessandro1997/the-codeless-code#415]
I only want to ask you a few questions.

1) Can I use double names? (ex: José María)
2) Should I give two translations? A direct translation without the rhymes and the coincidence with names and words (Agnes-App, Boris-Build, etc.), and a free-style rhymed translation

**Comment by cdlm** [comment]
It would be fun if the alternate translation showed when hovering the mouse over the paragraph :)

**Comment by QilessQi** [comment]
1)  As usual, you can translate however you want.... double names are
fine.  My advice is to read it out loud to see that it scans and sounds
good.  :-)

2)  You are absolutely welcome to give multiple translations.  I would not
dare to refuse you.    :-)
